# Generated by Django 5.2.3 on 2025-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('diseases', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
