# Generated by Django 5.2.3 on 2025-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=150)),
                ('gender', models.CharField(max_length=6)),
                ('visiteddate', models.DateTimeField(auto_now=True)),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eysystem.doctors')),
            ],
        ),
    ]
