# Generated by Django 5.2.3 on 2025-06-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eysystem', '0003_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('presdate', models.DateField(auto_now=True)),
                ('medicine', models.TextField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eysystem.patient')),
            ],
        ),
    ]
