# Generated by Django 5.2.3 on 2025-06-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eysystem', '0004_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eysystem.prescription')),
            ],
        ),
    ]
