# Generated by Django 5.2.3 on 2025-06-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eysystem', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='medicine',
            new_name='Prescriptionid',
        ),
    ]
