# Generated by Django 5.2.3 on 2025-06-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eysystem', '0006_rename_medicine_payment_prescriptionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Prescriptionid',
            new_name='madicine_Prescriptionid',
        ),
    ]
